SRC += features/achordion.c

VIA_ENABLE          = no

DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes

COMBO_ENABLE = yes

AUTOCORRECT_ENABLE = yes

OLED_ENABLE     = yes
LTO_ENABLE      = yes

REPEAT_KEY_ENABLE = yes

COMMAND_ENABLE = no

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
